POST http://localhost:3000/account/register
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST http://localhost:3000/account/login
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST http://localhost:3000/account/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiJ9.cGF2ZWwzQGxvY2FsaG9zdC5sb2NhbA.E0Ir7xbLVPScQ8QSw5VW98bu1mVkk12Akvftn8uP8Qke"
}
