POST http://localhost:3000/account/register
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST http://localhost:3000/account/login
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST http://localhost:3000/account/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGY3ZmFjOTg0NDIzNGJhZjIxOTFhZSIsImVtYWlsIjoicGF2ZWxAbG9jYWxob3N0LmxvY2FsIiwiaWF0IjoxNjM2Nzk0Mjg0fQ.FbPS2239Rzhw7dcd-03xZWABSs4ATFgaEM2bFmA6vbk"
}

###
POST http://localhost:3000/contacts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGY3ZmFjOTg0NDIzNGJhZjIxOTFhZSIsImVtYWlsIjoicGF2ZWxAbG9jYWxob3N0LmxvY2FsIiwiaWF0IjoxNjM2Nzk0MzY0LCJleHAiOjE2MzY3OTQ5NjR9.6jW-shHYLC63Aro29IIVlyxqibWzKU8Ohv85uCDCPug
Content-Type: application/json

{
    "lastName": "Oskarek",
    "firstName": "Morce",
    "address": "Doometshek Yikohvi oobookey, Booneenah",
    "phone": "34234234"
}
