POST https://strv-addressbook-knotek-pavel.herokuapp.com/account/register
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST https://strv-addressbook-knotek-pavel.herokuapp.com/account/login
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST https://strv-addressbook-knotek-pavel.herokuapp.com/account/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGMyNmFjOGJlYTRiMTRhZDY4YjE0NSIsImVtYWlsIjoicGF2ZWxAbG9jYWxob3N0LmxvY2FsIiwiaWF0IjoxNjM2NTc3NDQ1fQ.KNOiBRsXIP629aJjdlB-9bf8rvCaKLUonxUtTjQHoKQ"
}

###
POST https://strv-addressbook-knotek-pavel.herokuapp.com/contacts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGU2ZDI5ZDIwZmY3YmFmZTJhYWI4MCIsImVtYWlsIjoicGF2ZWxAbG9jYWxob3N0LmxvY2FsIiwiaWF0IjoxNjM2NzI3ODI1LCJleHAiOjE2MzY3MjgxMjV9.34yNPxim1O1s_TXFo26APaxO5RFNKWO1HKVq176wZrQ
Content-Type: application/json

{
    "lastName": "Morce",
    "firstName": "Oskar",
    "address": "Doometshek Yikohvi oobookey"
}
