POST https://strv-addressbook-knotek-pavel.herokuapp.com/account/register
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST https://strv-addressbook-knotek-pavel.herokuapp.com/account/login
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST https://strv-addressbook-knotek-pavel.herokuapp.com/account/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGU2ZDI5ZDIwZmY3YmFmZTJhYWI4MCIsImVtYWlsIjoicGF2ZWxAbG9jYWxob3N0LmxvY2FsIiwiaWF0IjoxNjM2NzkwOTY1fQ.5i6XXP4_ieY8Aw0asHzNfvZDYdZAMzMaE6kbcIlSOtg"
}

###
POST https://strv-addressbook-knotek-pavel.herokuapp.com/contacts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGU2ZDI5ZDIwZmY3YmFmZTJhYWI4MCIsImVtYWlsIjoicGF2ZWxAbG9jYWxob3N0LmxvY2FsIiwiaWF0IjoxNjM2NzkwOTQ5LCJleHAiOjE2MzY3OTEyNDl9.pJTXE2B-ZS4krJ5B1S8P4N8qu98ecclcURRqxhjk_ec
Content-Type: application/json

{
    "lastName": "Morce",
    "firstName": "Oskar",
    "address": "Doometshek Yikohvi oobookey"
}
