POST http://localhost:3000/account/register
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST http://localhost:3000/account/login
Content-Type: application/json

{
    "email": "pavel@localhost.local",
    "password": "MyP4ssw0rd."
}
###
POST http://localhost:3000/account/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiJ9.cGF2ZWxAbG9jYWxob3N0LmxvY2Fs.ITIkPSJOOcZ3t-p8BN6tHslGOAmu5ajK1nTSv2rCxCM"
}

###
POST http://localhost:3000/contacts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdmVsQGxvY2FsaG9zdC5sb2NhbCIsImlhdCI6MTYzNjU3NDg5MiwiZXhwIjoxNjM2NTc1MTkyfQ.MhoasT3bRLGeAknqKeO534bM-zcdhbMKV-Ze5am0dVY
Content-Type: application/json

{
    "lastName": "Barel",
    "firstName": "Karel",
    "address": "Doometshek Yikohvi oobookey"
}
